/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStudentsRouteImport } from './routes/api/students'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGpaRouteImport } from './routes/api/gpa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsRoute = ApiStudentsRouteImport.update({
  id: '/api/students',
  path: '/api/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGpaRoute = ApiGpaRouteImport.update({
  id: '/api/gpa',
  path: '/api/gpa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/gpa': typeof ApiGpaRoute
  '/api/health': typeof ApiHealthRoute
  '/api/students': typeof ApiStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/gpa': typeof ApiGpaRoute
  '/api/health': typeof ApiHealthRoute
  '/api/students': typeof ApiStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/gpa': typeof ApiGpaRoute
  '/api/health': typeof ApiHealthRoute
  '/api/students': typeof ApiStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/gpa' | '/api/health' | '/api/students'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/gpa' | '/api/health' | '/api/students'
  id: '__root__' | '/' | '/api/gpa' | '/api/health' | '/api/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGpaRoute: typeof ApiGpaRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStudentsRoute: typeof ApiStudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students': {
      id: '/api/students'
      path: '/api/students'
      fullPath: '/api/students'
      preLoaderRoute: typeof ApiStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gpa': {
      id: '/api/gpa'
      path: '/api/gpa'
      fullPath: '/api/gpa'
      preLoaderRoute: typeof ApiGpaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGpaRoute: ApiGpaRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStudentsRoute: ApiStudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
